### ISSUE TITLE
searchApp is no longer working

### ISSUE THREAD

**Issue by sfh1182** [liato/android-market-api-py#1]
For instance, when I try:

results = session.searchApp("Education", entriesCount = 10, startIndex=0)

...I get an empty list returned.  Any ideas?

**Comment by andrewmlevy** [comment]
ran into the same issue

**Comment by khiro** [comment]
you need to set the correct android id which is found in Gtalk service monitor (star sharp star sharp 8255 sharp star sharp star)
i can get search result, following code. 
session = MarketSession()
session.login("user@gmail.com", "password")
session.context.androidId = "ANDROID_ID"
results = session.searchApp("Application Name")

**Comment by fdw-fth** [comment]
Hello,
I have the same problem here, I added the line you specified but it gives this error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "androidmarket.py", line 155, in searchApp
    response = self.execute(request)
  File "androidmarket.py", line 145, in execute
    raise RequestError(e)
androidmarket.RequestError: HTTPError()

Could someone help me ? 
Thanks

**Comment by khiro** [comment]
Hello ferodia,

Did you set correct android id ?
Android id is alphabet and digit combination strings of 16 length.
You can find it in Gtalk service monitor's "Device ID: android-XXXXXXXXXXXXXXXX"
Please check it.

**Comment by fdw-fth** [comment]
It works now, the problem was that android ID I was using is banned, so I had to use another one.

**Comment by fdw-fth** [comment]
Hi,
Actually the one I had apprently wasn't working anymore so I used a new one
and now it's working. Thanks for your help

2012/1/5 khiro <
reply@reply.github.com

> Hello ferodia,
> 
> Did you set correct android id ?
> Android id is alphabet and digit combination strings of 16 length.
> You can find it in Gtalk service monitor's "Device ID:
> android-XXXXXXXXXXXXXXXX"
> Please check it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/liato/android-market-api-py/issues/1#issuecomment-3369645

## 

Fadwa FATHALLAH
lve ingnieur  TELECOM ParisTech / Institut EURECOM
prsidente du BDE EURECOM
06 58 70 09 20

**Comment by liato** [comment]
Thanks for your help @khiro. I guess I can close this issue now.
