### ISSUE TITLE
Do you have installation instructions or advice?

### ISSUE THREAD

**Issue by mittenchops** [liato/android-market-api-py#9]
I cloned the repo and tried a simple keyword search, but got the error

```
Traceback (most recent call last):
  File "getapps.py", line 5, in <module>
    import market_proto
  File "/home/me/androidmarket/market_proto.py", line 3, in <module>
    from google.protobuf import descriptor
ImportError: No module named google.protobuf
```

I assume this is because I don't have the java android-market-api installed in the right place?  Do I just dump that in the same folder as android-market-api-py?  Or should this work?

**Comment by liato** [comment]
As mentioned in the "[Requirements](https://github.com/liato/android-market-api-py/blob/master/README.md#requirements)" section in the readme you have to install [protobuf](http://pypi.python.org/pypi/protobuf/2.4.1) for python.
Use either easy_install or pip to install it.
